#!/usr/bin/perl
#get data from EVENTBIN generated by FLUKA
#EVENTBIN saves each event including hit energy and pixel.
print "Please input [mass]\n";
$numArgs = $#ARGV + 1;
if( $numArgs < 1){
    print "You miss arguments\n";
}elsif( $numArgs >1){
    print "You have too many arguments\n";
}
my $mass = $ARGV[0];
print($ERG,"\n");
use warnings;
use strict;

for (my $i=-5; $i<=5;$i++){
    print($i);
    my $erg = "1e".$i;
    my $outputlog = "log_".$mass."GeV_".$erg."GeV.txt";
    my $outputin = "monopole_".$erg."GeV.in";
    my $outputroot = "monopole_".$mass."GeV_".$erg."GeV.root";
    system("./replace.pl $erg");
    system("./monopole $outputin >& $outputlog");
    system("mv monopole.root $outputroot");
}
